/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Q1 from 'src/components/Q1/Q1';

const DetailsSection1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1111px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const DetailsPage = styled(Q1)(({ theme }) => ({
  width: `1440px`,
  height: `1111px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

function DetailsSection(props) {
  return (
    <DetailsSection1 className={props.className}>
      <DetailsPage />
    </DetailsSection1>
  );
}

export default DetailsSection;
