
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_START ="LOGIN_START";
// RESET PASSWORD ACTIONS
export const SEND_EMAIL_RESPONSE = 'RESET_PASSWORD_RESPONSE';
export const SENDING_EMAIL_START = 'SENDING_EMAIL_START';
export const SENDING_EMAIL_SUCCESS = 'SENDING_EMAIL_SUCCESS';
export const SENDING_EMAIL_ERROR = 'SENDING_EMAIL_ERROR';
export const UPDATING_PASSWORD_START = 'UPDATING_PASSWORD_START';
export const UPDATING_PASSWORD_FAIL = 'UPDATING_PASSWORD_FAIL';
export const UPDATING_PASSWORD_SUCCESS = 'UPDATING_PASSWORD_SUCCESS';
export const UPDATING_PASSWORD_ERROR = 'UPDATING_PASSWORD_ERROR';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
