export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_PAYLOAD = "LOGIN_PAYLOAD";

// RESET PASSWORD ACTIONS
export const SEND_EMAIL_RESPONSE = "RESET_PASSWORD_RESPONSE";
export const SENDING_EMAIL_START = "SENDING_EMAIL_START";
export const SENDING_EMAIL_SUCCESS = "SENDING_EMAIL_SUCCESS";
export const SENDING_EMAIL_ERROR = "SENDING_EMAIL_ERROR";
export const UPDATING_PASSWORD_START = "UPDATING_PASSWORD_START";
export const UPDATING_PASSWORD_FAIL = "UPDATING_PASSWORD_FAIL";
export const UPDATING_PASSWORD_SUCCESS = "UPDATING_PASSWORD_SUCCESS";
export const UPDATING_PASSWORD_ERROR = "UPDATING_PASSWORD_ERROR";
export const USER_NOT_FOUND = "USER_NOT_FOUND";

// Create product actions
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_START = "PRODUCT_CREATE_START";

// PRODUCT
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_RELATED_PRODUCTS = "FETCH_RELATED_PRODUCTS";
export const FETCH_RELATED_PRODUCTS_ERROR = "FETCH_RELATED_PRODUCTS_ERROR";

// PAYMENT
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILURE = "PAYMENT_FAILURE";
export const PAYMENT_ERROR = "PAYMENT_ERROR";
export const PAYMENT_START = "PAYMENT_START";

//HANDE CLICK
export const IS_CLICKED = "IS_CLICKED";

//update Product
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_START = "PRODUCT_UPDATE_START";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const VIEW_PRODUCT = "VIEW_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

/**
 * DELETE PRODUCT IN SELLER COLLECTION
 */
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCTS_ERROR";
// ADDING TO CART ACTIONS
export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
// VIEW CART
export const VIEW_CART_SUCCESS = "VIEW_CART_SUCCESS";
export const VIEW_CART_ERROR = "VIEW_CART_ERROR";
export const VIEW_CART_START = "VIEW_CART_START";

//DELETE ONE ITEM IN CART
export const REMOVE_ONE_ITEM_CART = "REMOVE_ONE_ITEM_CART";
export const REMOVE_ONE_ITEM_CART_SUCCESS = "REMOVE_ONE_ITEM_CART_SUCCESS";
export const REMOVE_ONE_ITEM_CART_ERROR = "REMOVE_ONE_ITEM_CART_ERROR";

//clear cart
export const CLEAR_CART = "CLEAR_CART";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_ERROR = "CLEAR_CART_ERROR";
// UPDATING PRODUCT QUANTITY IN CART
export const UPDATE_TO_CART_START = "UPDATE_TO_CART_START";
export const UPDATE_TO_CART_SUCCESS = " UPDATE_TO_CART_SUCCESS";
export const UPDATE_TO_CART_ERROR = "UPDATE_TO_CART_ERROR";
// add to wishlist
export const ADD_TO_WISHLIST_ERROR = "ADD_TO_WISHLIST_ERROR";
export const ADD_TO_WISHLIST_START = "ADD_TO_WISHLIST_START";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";

// view wishlist
export const VIEW_WISHLIST_START = "VIEW_WISHLIST_STAR";
export const VIEW_WISHLIST_SUCCESS = "VIEW_WISHLIST_SUCCESS";
export const VIEW_WISHLIST_ERROR = "VIEW_WISHLIST_ERROR";

//remove from wish list
export const REMOVE_FROM_WISHLIST_ERROR = "REMOVE_FROM_WISHLIST_ERROR";
export const REMOVE_FROM_WISHLIST_START = "REMOVE_FROM_WISHLIST_START";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";

// CHAT
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAIL = "GET_CHAT_FAIL";

//CATEGORY
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_ERROR = "FETCH_CATEGORY_ERROR";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
//NOTIFICATION
export const VIEW_NOTIFICATION_START = "VIEW_NOTIFICATION_START";
export const VIEW_NOTIFICATION_SUCCESS = "VIEW_NOTIFICATION_SUCCESS";
export const VIEW_NOTIFICATION_ERROR = "VIEW_NOTIFICATION_ERROR";
// open model
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
// Disable an account
export const DISABLE_USER_START = "DISABLE_USER_START";
export const DISABLE_USER_SUCCESS = "DISABLE_USER_SUCCESS";
export const DISABLE_USER_FAIL = "DISABLE_USER_FAIL";
//Enable an account
export const ENABLE_USER_START = "ENABLE_USER_START";
export const ENABLE_USER_SUCCESS = "ENABLE_USER_SUCCESS";
export const ENABLE_USER_FAIL = "ENABLE_USER_FAIL";
