export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_START = 'LOGIN_START';
// RESET PASSWORD ACTIONS
export const SEND_EMAIL_RESPONSE = 'RESET_PASSWORD_RESPONSE';
export const SENDING_EMAIL_START = 'SENDING_EMAIL_START';
export const SENDING_EMAIL_SUCCESS = 'SENDING_EMAIL_SUCCESS';
export const SENDING_EMAIL_ERROR = 'SENDING_EMAIL_ERROR';
export const UPDATING_PASSWORD_START = 'UPDATING_PASSWORD_START';
export const UPDATING_PASSWORD_FAIL = 'UPDATING_PASSWORD_FAIL';
export const UPDATING_PASSWORD_SUCCESS = 'UPDATING_PASSWORD_SUCCESS';
export const UPDATING_PASSWORD_ERROR = 'UPDATING_PASSWORD_ERROR';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';

// Create product actions

export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL';
export const PRODUCT_CREATE_START = 'PRODUCT_CREATE_START';
// PRODUCT
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
//HANDE CLICK
export const IS_CLICKED = 'IS_CLICKED';
