export const actionTypes = {
	FETCHING_USERS_START: 'FETCHING_USERS_START',
	FETCHING_USERS_SUCCEED: 'FETCHING_USERS_SUCCEED',
	FETCHING_USERS_FAIL: 'FETCHING_USERS_FAIL',
	CHANGE_PAGE: 'CHANGE_PAGE',
};
