name: Test
on:
  push:
    branches: "**"
  pull_request:
    branches: "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests and coverage
        run: npm test && ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info

        env:
          CI: true
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
